### ISSUE TITLE
Question for TA

### ISSUE THREAD

**Issue by minhnhat1901** [phuanh004/cse-120#3]
- [x] For `write4.c` file, does it need to show what we type out on the terminal? (Đánh chữ lên terminal bị mất, nhưng Enter thì nó hiện ra cả string) [[Here]](https://github.com/phuanh004/cse-120/issues/3#issuecomment-1811639576)
- [x] For `handleUnlink`, does it need to check if string is not null or string has a length of 0? (`(s != null)` or `s != null || s.length == 0`)
- [x] #8
- [ ] In `handleExit` function, it asks to wake up the parent but not sure where and how.
- [x] `except1.c` can't pass. Why? [[Here]](https://github.com/phuanh004/cse-120/issues/3#issuecomment-1811632979)
- [x] Page size only `14` , from in & out
- [ ] readVirtualMemory function: hỏi logic đúng ko? [[Here]](https://github.com/phuanh004/cse-120/issues/3#issuecomment-1811633594)
     - Check virtual address if valid
     - Chạy loop để read byte. Initial = 0 tới khi bằng length.
     - Check valid chỗ pageTable đúng ko?
     - Tính VPN
     - Check mấy cái bound >= xem đúng ko
     - Lấy amount từ cái lượng array tiếp theo.
- [ ] writeVirtualMemory.
- [x] allocatePage: tạo 
- [x] How to test user and system call [[Here]](https://github.com/phuanh004/cse-120/issues/3#issuecomment-1811637406)
- [ ] Coi test được Condition ko

**Comment by phuanh004** [comment]
413 userprocess, need check

**Comment by minhnhat1901** [comment]
exit -> use similar idea as KThread.finish() function

**Comment by phuanh004** [comment]
# `except1.c` can't pass. Why?
Fix handleExept, default case

**Comment by minhnhat1901** [comment]
In the readVirtualMemory function,
- Make some test case to test out 3 different cases:
1) Access to the beginning of the first page of virtual memory and end at the end of the last address of virtual memory
2) Access to the middle of the first page of virtual memory and end at the end of the last address of virtual memory
3) Access to the middle of the first page of virtual memory and end at the middle of the last address of virtual memory

**Comment by phuanh004** [comment]
## How to test user and system call
call pid

**Comment by phuanh004** [comment]
##  Where should we use `waitUntil`? In `waitUntil`, it has a time count parameter, but how we can keep track the time here

We do not have to, nachos auto use the alarm

**Comment by phuanh004** [comment]
## For write4.c file, does it need to show what we type out on the terminal? (Đánh chữ lên terminal bị mất, nhưng Enter thì nó hiện ra cả string)

It's okay
